---
name: Build NetworkManager-ssh Fedora Rawhide

on:
  push:
    branches: [main]
  pull_request:
    branches: ["**"]

jobs:
  call-build:
    uses: ./.github/workflows/build_fedora.yml
    with:
      fedora-version: rawhide
